eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true

spring:
    cloud:
      bus:
        trace:
          enabled: true #开启消息总线
        enabled: true
  


