spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.107:3306/sys-blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 5678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

 rabbitmq:
    host: 192.168.3.163
    port: 5672
    username: rabbitadmin
    password: 123456
    publisher-confirms: true
    virtual-host: /

server:
  port: 9997
